project_id = "ztk"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:8081"
additional_redirect_urls = [
    "http://localhost:19006",
    "exp://localhost:8081",
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_confirmations = false
